### PR TITLE
Turn Choc key socket footprint 180 degree.

### PR DESCRIPTION
**Pull request by yoichiro**
I think that the two key socket footprints have an issue about the direction of the Kailh Choc V1 socket.

As-Is:

Screenshot_20210121_132244

To-Be:

Screenshot_20210121_132344

See: [Kailh Choc ソケットの方向について - Self-Made Keyboards in Japan](https://scrapbox.io/self-made-kbds-ja/Kailh_Choc_%E3%82%BD%E3%82%B1%E3%83%83%E3%83%88%E3%81%AE%E6%96%B9%E5%90%91%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

### CODE REVIEW

**Comment by yoichiro** [comment]
@foostan How about this?

**Comment by foostan** [comment]
Sorry, I'm late. I'll check it today 🙏

**Comment by yoichiro** [comment]
No problem. Thanks!

**Comment by foostan** [comment]
@yoichiro LGTM! Thanks 🙏

**Comment by yoichiro** [comment]
@foostan Great! Thank you for reviewing and merging.

**Pull request merged**
